### ISSUE TITLE
Angular speed calculation in particle collider

### ISSUE THREAD

**Issue by SuomiKP31** [TheAllenChou/unity-cj-lib#4]
I decided to do something to GPU Particles With Colliders section, in particular, add angular speed calculation functionalities to Physics.cginc. I've already read associated codes but still have some questions.
Firstly, why didn't you include angular speed calculation in the code?  Have you encountered some problems unsolvable during the original development process? Or you just thought it's too complicated to consider that back then? 
More specifically, I read GPU Gems Chapter 29, it says in order to get a torque on a rigidbody we'll need to have a center of mass. Your code seems to treat all particles as spheres so the center of mass is always the sphere center... So it is not possible to calculate the torque of the particles? However I do think we can somehow simulate angular speed damping because we have the friction force present.

So that's the proposal. I'm planning to do this as one of my course projects. Will you allow me to do modifications on your project(I'll do them in a seperated project and if I finish it I'll send it to you), and do you think my thoughts are viable?

**Comment by TheAllenChou** [comment]
I just didn't feel like spending the extra time to implement the angular part of collision resolution. Laziness was the reason.

**Comment by TheAllenChou** [comment]
I just didn't feel like spending the extra time to implement the angular part of collision resolution. Laziness was the reason :p

**Comment by SuomiKP31** [comment]
Thanks. I'll try to implement it. It seems viable to calculate torque from friction while ignoring the repulsive force... Since repulsive force is always along the relative position vector.
